### ISSUE TITLE
Update --debug to check for browser in path

### ISSUE THREAD

**Issue by caffo** [caffo/roam-to-git#10]
Depends on #9 

Ensure `--debug` checks for a browser and tell the user to use `--browser-path`  or add a browser to their path.

**Comment by mrnninster** [comment]
Created a PR for this #15

**Comment by mrnninster** [comment]
I had closed this before seeing your response since you have merged #15 to master this has been fixed

**Comment by caffo** [comment]
```
<datetime> | DEBUG    | roam_to_git.__main__:main:97 - use --browser-path <browser_path> to specify a browser path
<datetime> | ERROR    | roam_to_git.__main__:main:98 - Please specify a firefox/chrome browser path
```

Debug should say something like

```Browser not detected. Please have one in your path or use --browser-path <browser_path> to specify it.```

**Comment by mrnninster** [comment]
This should be reolved with #16

**Comment by mrnninster** [comment]
Kindly review this on the #16 
Test are now passing a well
