### ISSUE TITLE
Make --browser-version optional

### ISSUE THREAD

**Issue by caffo** [caffo/roam-to-git#9]
Assuming a valid browser is available in $PATH, try to use it if --browser-version is not passed. Return an error if no browser is found and --browser-version is not passed.

**Comment by mrnninster** [comment]
I had also reopened this 
This is also fixed in PR #15

**Comment by caffo** [comment]
It fails both with and without the browser path in an action:

with `--browser-version firefox`:

```
2023-05-01 16:01:59.584 | DEBUG    | roam_to_git.__main__:main:80 - No secret found at /home/runner/work/roam/roam/.env
2023-05-01 16:01:59.584 | ERROR    | __main__:<module>:8 - An error has been caught in function '<module>', process 'MainProcess' (1987), thread 'MainThread' (14056[15](https://github.com/caffo/roam/actions/runs/4852631619/jobs/8647861126#step:7:16)88484992):
Traceback (most recent call last):
> File "/opt/hostedtoolcache/Python/3.8.[16](https://github.com/caffo/roam/actions/runs/4852631619/jobs/8647861126#step:7:17)/x64/bin/roam-to-git", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7fd709d7ff70>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 110, in main
    browser_path=BROWSER_PATH)

UnboundLocalError: local variable 'BROWSER_PATH' referenced before assignment
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/bin/roam-to-git", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/loguru/_logger.py", line 1149, in catch_wrapper
    return function(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/roam_to_git/__main__.py", line 110, in main
    browser_path=BROWSER_PATH)
UnboundLocalError: local variable 'BROWSER_PATH' referenced before assignment
Error: Process completed with exit code 1.
```

without it:

![image](https://user-images.githubusercontent.com/456/235483944-edb8955f-5b54-4fd9-9986-bf4b5c48a1b3.png)

**Comment by mrnninster** [comment]
This should be resolved in #16

**Comment by mrnninster** [comment]
Kindly review this on the #16 
Test are now passing a well

**Comment by caffo** [comment]
Still breaking after #16 is merged:

<img width="1667" alt="CleanShot 2023-05-02 at 15 00 08@2x" src="https://user-images.githubusercontent.com/456/235747569-4fda8466-e629-4f00-b16a-020f95307a08.png">

And if I pass `--browser-path firefox`,  I get infinite `Sign In failed` errors:

<img width="1110" alt="CleanShot 2023-05-02 at 15 02 40@2x" src="https://user-images.githubusercontent.com/456/235747927-5576b9b6-d8f8-4ee5-807b-2f7d18ec254d.png">

**Comment by mrnninster** [comment]
Was this working before the PR was merged

Also it looks to me that you are using it as part of a workflow can I get that workflow so I can try it out myself

This is my run of app

![roam_logs](https://user-images.githubusercontent.com/41529409/235905050-c6bf7d28-7dd6-454a-9182-29cad00ed2cc.png)

There are no sign in failures and the initial error only happens beacuse i don't actually have firefix in the directory

If I am not wrong you mentioned the infinite sign in before and the IP getting black listed, and you asked me to add a 5 attempt limit

**Comment by caffo** [comment]
I will add you to the demo repo so you can test the action.

**Comment by caffo** [comment]
Done, please check https://github.com/caffo/roam-to-git-demo/
